version: "3.9"
services:
  server:
    build:
      context: .
      target: 'base'
    command: "yarn start"
    environment:
      PORT: 80
    volumes:
      - .:/server
    ports:
      - "3001:80"